language: android
jdk: oraclejdk8

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra
  - addon

before_script:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - ./gradlew prado:build