language: android
jdk: oraclejdk8

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra
  - addon

script:
  - ./gradlew prado:build